/**
 * The ticket contract, shared by both sides — US-40.
 *
 * The spine: nineteen of the twenty-eight stories in the MVP slice touch this.
 */
import { z } from 'zod';

import { ChannelSchema } from './customer.js';
import { TicketViewSchema } from './ticket-counts.js';
import { PaginationQuerySchema } from '../api/pagination.js';

/** Matches `TicketStatus` in the Prisma schema. */
export const TicketStatusSchema = z.enum([
  'NEW',
  'OPEN',
  'PENDING_CUSTOMER',
  'PENDING_INTERNAL',
  'ESCALATED',
  'RESOLVED',
  'CLOSED',
]);
export type TicketStatus = z.infer<typeof TicketStatusSchema>;

/** Matches `TicketPriority` in the Prisma schema. */
export const TicketPrioritySchema = z.enum(['LOW', 'MEDIUM', 'HIGH', 'URGENT']);
export type TicketPriority = z.infer<typeof TicketPrioritySchema>;

/**
 * How a ticket stands against its SLA.
 *
 * Derived from the due dates denormalised onto the ticket, not stored — so it
 * cannot go stale between the clock passing and something noticing. `none`
 * means no policy applies, which is different from "on track".
 */
export const SlaStateSchema = z.enum(['none', 'ok', 'warn', 'breach']);
export type SlaState = z.infer<typeof SlaStateSchema>;

export const CreateTicketSchema = z.object({
  customerId: z.string().uuid(),
  subject: z.string().trim().min(3).max(200),
  description: z.string().trim().max(20_000).optional(),
  categoryId: z.string().uuid().optional(),
  priority: TicketPrioritySchema.optional(),
  departmentId: z.string().uuid().optional(),
  branchId: z.string().uuid().optional(),
  channel: ChannelSchema.default('WEB'),
  tags: z.array(z.string().trim().min(1).max(40)).max(20).optional(),
});

export type CreateTicket = z.infer<typeof CreateTicketSchema>;

/**
 * Everything a ticket's own fields can become.
 *
 * `status` is deliberately **absent**: moving a ticket through its lifecycle is
 * US-47's transition endpoint, which validates that the move is legal. Allowing
 * it here would be a second, unguarded door onto the same state machine.
 */
export const UpdateTicketSchema = z.object({
  subject: z.string().trim().min(3).max(200).optional(),
  description: z.string().trim().max(20_000).nullable().optional(),
  categoryId: z.string().uuid().nullable().optional(),
  priority: TicketPrioritySchema.optional(),
  departmentId: z.string().uuid().nullable().optional(),
  branchId: z.string().uuid().nullable().optional(),
  assigneeId: z.string().uuid().nullable().optional(),
  tags: z.array(z.string().trim().min(1).max(40)).max(20).optional(),
});

export type UpdateTicket = z.infer<typeof UpdateTicketSchema>;

/** AC2 — every one of these reaches the database. */
export const TicketListQuerySchema = PaginationQuerySchema.extend({
  /**
   * One of the queue's view tabs — US-42, AC4.
   *
   * A named view rather than the caller assembling the same filters by hand, so
   * the tab, its count and the list it produces all come from one definition.
   */
  view: TicketViewSchema.optional(),
  q: z.string().trim().max(200).optional(),
  status: TicketStatusSchema.optional(),
  priority: TicketPrioritySchema.optional(),
  categoryId: z.string().uuid().optional(),
  assigneeId: z.string().uuid().optional(),
  /** `unassigned` is a real filter, and the one an agent picking up work uses. */
  unassigned: z.enum(['true']).optional(),
  departmentId: z.string().uuid().optional(),
  branchId: z.string().uuid().optional(),
  channel: ChannelSchema.optional(),
  slaState: SlaStateSchema.optional(),
  createdFrom: z.string().datetime().optional(),
  createdTo: z.string().datetime().optional(),
  sort: z.enum(['createdAt', 'updatedAt', 'priority', 'sla', 'number']).optional(),
  dir: z.enum(['asc', 'desc']).optional(),
});

export type TicketListQuery = z.infer<typeof TicketListQuerySchema>;

/** Just enough of a customer to render a ticket row or header. */
export const TicketCustomerSchema = z.object({
  id: z.string().uuid(),
  firstName: z.string(),
  lastName: z.string(),
  email: z.string().nullable(),
  companyName: z.string().nullable(),
});

export const TicketSlaSchema = z.object({
  state: SlaStateSchema,
  firstResponseDueAt: z.string().datetime().nullable(),
  resolutionDueAt: z.string().datetime().nullable(),
  firstResponseBreached: z.boolean(),
  resolutionBreached: z.boolean(),
  /** Negative once the target has passed. Null when no policy applies. */
  secondsRemaining: z.number().int().nullable(),
});

export const TicketSchema = z.object({
  id: z.string().uuid(),
  /** The human-facing reference. Sequential, generated by PostgreSQL. */
  number: z.number().int().positive(),
  subject: z.string(),
  status: TicketStatusSchema,
  priority: TicketPrioritySchema,
  channel: ChannelSchema,
  customer: TicketCustomerSchema,
  assigneeId: z.string().nullable(),
  assigneeName: z.string().nullable(),
  categoryId: z.string().nullable(),
  /**
   * The category as a person reads it — US-42, AC1.
   *
   * Bilingual, resolved server-side from the caller's locale rather than sent
   * as a pair, because the queue renders one of them and shipping both to
   * render one is a column of dead weight on every row.
   */
  categoryName: z.string().nullable(),
  departmentId: z.string().nullable(),
  branchId: z.string().nullable(),
  tags: z.array(z.string()),
  sla: TicketSlaSchema,
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export type Ticket = z.infer<typeof TicketSchema>;

export const TicketMessageSchema = z.object({
  id: z.string().uuid(),
  senderType: z.enum(['AGENT', 'CUSTOMER', 'SYSTEM']),
  authorName: z.string().nullable(),
  body: z.string(),
  /**
   * **The project's first non-negotiable rule lives on this field.**
   *
   * An internal note must never reach a customer. The portal API (US-82)
   * filters on it in the query, not in the UI — this flag is a contract for the
   * staff client, never a permission.
   */
  isInternal: z.boolean(),
  createdAt: z.string().datetime(),
});

export const TicketHistoryEntrySchema = z.object({
  id: z.string().uuid(),
  eventType: z.string(),
  field: z.string().nullable(),
  fromValue: z.string().nullable(),
  toValue: z.string().nullable(),
  actorName: z.string().nullable(),
  /**
   * The automation that caused this, when nothing human did — US-50, AC3.
   *
   * Exactly one of `actorName` and `automationRule` is set. Attributing an SLA
   * escalation to whoever happened to touch the ticket last would be a lie in
   * the one record kept for settling disputes.
   */
  automationRule: z.string().nullable(),
  createdAt: z.string().datetime(),
});

export const TicketAttachmentSchema = z.object({
  id: z.string().uuid(),
  fileName: z.string(),
  contentType: z.string(),
  sizeBytes: z.number().int().nonnegative(),
});

/**
 * AC3 — the whole workspace in one response.
 *
 * The ticket screen would otherwise cost five round trips, and each of them
 * would be a separate spinner on the same page.
 */
export const TicketDetailSchema = TicketSchema.extend({
  description: z.string().nullable(),
  messages: z.array(TicketMessageSchema),
  attachments: z.array(TicketAttachmentSchema),
  history: z.array(TicketHistoryEntrySchema),
  resolvedAt: z.string().datetime().nullable(),
  closedAt: z.string().datetime().nullable(),
  reopenCount: z.number().int().nonnegative(),
});

export type TicketDetail = z.infer<typeof TicketDetailSchema>;
export type TicketMessage = z.infer<typeof TicketMessageSchema>;
export type TicketHistoryEntry = z.infer<typeof TicketHistoryEntrySchema>;
